#!/bin/sh

export H="$PWD"

if [ ! -r "$H"/config ]; then
    printf -- "couldn't read configuration file: %s\n" "$H/config"
    printf -- "copy %s to %s and edit appropriately\n" "$K/config.stage0" "$H/config"
    exit 1
fi

# enable verbose printing, abord on error
set -e -x

. "$H"/config
mkdir -p "$K" "$C" "$S" "$R" "$LOGPATH"

. "$H"/utils/utils
. "$H"/utils/prepare-rootfs
. "$H"/utils/build-butch

# NOTE
# installation starts all over if installed.dat is not there.
# to manually continue a stage0 build, run
#     $S/butch.bin install stage0
# in case the build failed or was interrupted.
rm -f "$S"/pkg/installed.dat

# update-buildroot - copy to sources
cp -r "$H"/pkg "$S"/
cp -r "$H"/KEEP "$S"/

# build the thing
"$S"/butch.bin install stage0

