#!/bin/bash

set -e -x
export H=$(pwd)

. $H/config
. $H/utils/utils
. $H/utils/prepare-root
. $H/utils/build-butch

mkdir -p $S/logs

#remove installed.dat, so installation starts all over
#stage0 can be continued manually via $/butch.out install stage0
#in case the build failed or was interrupted.
rm -f $S/pkg/installed.dat

. $H/utils/update-chroot
$S/butch.out install stage0

