#!/bin/sh

uid="$(id -u)"
if [ "$uid" != "0" ]; then
    printf -- "need to be root. please enter password.\n"
    su -c "$0"
    exit $?
fi

export H="$PWD"
. "$H"/config

mkdir -p "$R"/src/tarballs

mount --rbind /dev "$R"/dev
mount --rbind /proc "$R"/proc
mount --bind "$C" "$R"/src/tarballs

echo "Entering chroot..."
chroot "$R" /bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w$ ' \
    /bin/sh --login

umount "$R"/src/tarballs
umount "$R"/dev/pts
umount "$R"/dev/shm
umount "$R"/dev
umount "$R"/proc

