#!/bin/bash

if [ $UID -ne 0 ]; then
  su -c $0
  exit $?
fi

export H=$(pwd)
. $H/config

mount --rbind /dev $R/dev
mount --rbind /proc $R/proc
mount --bind $C $S/tarballs

echo "Entering chroot..."
SHELL=/bin/sh chroot $R /bin/sh

umount $R/src/tarballs
umount $R/dev/pts
umount $R/dev/shm
umount $R/dev
umount $R/proc


