#!/bin/sh

tarxf https://github.com/downloads/rofl0r/butch/ butch-0.0.5 .tar.bz2 butch
filesize='58819'
sha512='59fb701684cfed02a6e9e10fd8a0e708388c4ec204e585aa065f704e9fbf8ccf23e80c816eb53eaba308f7f81bbb745c4ee92eb5d6fc46fe712f58d11c20f345'

filename="$S"/butch-0.0.5.tar.bz2

read sz _ <<EOF
$(du -b "$filename")
EOF

if [ "$sz" != "$filesize" ]; then
    printf -- "error: build-butch: wrong filesize. got: %d expected: %d\n" "$sz" "$filesize"
    exit 1
fi

read sha _ <<EOF
$(sha512sum "$filename")
EOF

if [ "$sha" != "$sha512" ]; then
    printf -- "error: build-butch: hash doesn't match.\n"
    exit 1
fi


./build.sh
cp butch/butch "$S"/butch.bin
cp "$filename" "$C"/

