#!/bin/sh

download() {
	while true ; do
		if ! wget -c $1 --no-check-certificate; then
			echo "trouble downloading $1, fix your connection. will sleep for 10 sec and loop until it works."
			sleep 10
		else
			# check if archive was completety downloaded
			# busybox' wget seem to be rather buggy
			if ! tar tf $2 >/dev/null ; then
				echo "partial download detected, retrying..."
			else
				break;
			fi

		fi
	done
}

# tarxf http://server/path/to/ file-1 .tar.gz [dirname]
tarxf() {
  cd $S
  [ -f $2$3 ] || download $1$2$3 $2$3
  rm -rf ${4:-$2}
  tar xf $2$3
  cd ${4:-$2}
}
